Class {
	#name : 'GlobalTreeTestObject',
	#superclass : 'Object',
	#instVars : [
		'one',
		'two',
		'three'
	],
	#category : 'GlobalTree-Core-Tests',
	#package : 'GlobalTree-Core-Tests'
}

{ #category : 'accessing' }
GlobalTreeTestObject >> one [

	^ one
]

{ #category : 'accessing' }
GlobalTreeTestObject >> one: anObject [

	one := anObject
]

{ #category : 'accessing' }
GlobalTreeTestObject >> three [

	^ three
]

{ #category : 'accessing' }
GlobalTreeTestObject >> three: anObject [

	three := anObject
]

{ #category : 'accessing' }
GlobalTreeTestObject >> two [

	^ two
]

{ #category : 'accessing' }
GlobalTreeTestObject >> two: anObject [

	two := anObject
]
