Class {
	#name : 'CanopyTestObject',
	#superclass : 'Object',
	#instVars : [
		'one',
		'two',
		'three'
	],
	#category : 'Canopy-Core-Tests',
	#package : 'Canopy-Core-Tests'
}

{ #category : 'accessing' }
CanopyTestObject >> one [

	^ one
]

{ #category : 'accessing' }
CanopyTestObject >> one: anObject [

	one := anObject
]

{ #category : 'accessing' }
CanopyTestObject >> three [

	^ three
]

{ #category : 'accessing' }
CanopyTestObject >> three: anObject [

	three := anObject
]

{ #category : 'accessing' }
CanopyTestObject >> two [

	^ two
]

{ #category : 'accessing' }
CanopyTestObject >> two: anObject [

	two := anObject
]
